### ISSUE TITLE
Unable to unlock Vault when using Session Key

### ISSUE THREAD

**Issue by landalex** [maxlaverse/terraform-provider-bitwarden#118]
I'm unable to fetch login items from a Bitwarden vault using the session key for auth. The error I get is:
```
╷
│ Error: unable to unlock Vault with provided session key (status: unauthenticated)
│
│   with provider["registry.terraform.io/maxlaverse/bitwarden"],
│   on main.tf line 9, in provider "bitwarden":
│    9: provider "bitwarden" {
│
╵
```

### Terraform Version
`1.7.3`

### Affected Resource(s)
- data.bitwarden_item_login

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    bitwarden = {
      source  = "maxlaverse/bitwarden"
      version = ">= 0.7.0"
    }
  }
}

provider "bitwarden" {
  session_key = "<redacted>"
}

data "bitwarden_item_login" "test" {
  id = "<redacted>"
}

output "bitwarden-test" {
  value = data.bitwarden_item_login.test.password
}
```

### Debug Output
https://gist.github.com/landalex/5f01579349ce7a90afdad1c1f197388e

### Panic Output
N/A

### Expected Behavior
The login item password should have been output

### Actual Behavior
The login item could not be loaded because the Bitwarden vault failed to unlock using the session key.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I tried setting the session key multiple ways (`BW_SESSION`, Terraform variable, and directly when initializing the provider as in this example) and they all fail with the same error.

I can successfully fetch this login item using the Bitwarden CLI with `bw get item <id>` in a terminal session via the `BW_SESSION` enviornment variable.

### References
N/A

**Comment by maxlaverse** [comment]
Hi @landalex 
Can you try the following, within your Terraform workspace ?
```
export BITWARDENCLI_APPDATA_DIR=./.bitwarden/
export BW_SESSION=<your-key>
bw status
```
It's to ensure the session key is valid.

**Comment by landalex** [comment]
When I do that, the `bw status` command reports that it is unauthenticated. I'm realizing now that the session key I'm using is for a different copy of the vault (defaults to `%APPDATA%` since I'm on Windows), and that's why it's not authenticated. Thanks for pointing me in the right direction :)

Do you see any problem with setting the `BITWARDENCLI_APPDATA_DIR` to my "default" location, so the Terraform provider reads from there rather than from `.bitwarden`? Will that default location be updated automatically or is that the reason the provider pulls the vault to the `.bitwarden` folder? My Terraform setup has one folder per environment so having separate sessions/`.bitwarden` folders per environment seems tedious, but I'm still figuring out the best way to work with this so I'd appreciate any guidance!

**Comment by maxlaverse** [comment]
Glad that's the issue, easy to solve :)

I didn't use the cli/provider in a lot of different situations tbh, outside of development. I don't expect any problem if you share the same Vault's location with your Terraform workspaces, and it probably even makes sense since the checked-out workspace is persisted across plan executions (doesn't sound like you're using it on a CI). Please let me know if you face any issue, I'd love to learn about that.

I chose to use a dedicated folder because I didn't want to risk Terraform messing with people's local Vault, in case they use a different username/server url for Terraform. Since there always seems to be a single Vault at a given time in the default location, sharing the location with different credentials/servers would mean a lot of re-pulling the Vaults, which I wanted to avoid.

**Comment by landalex** [comment]
Will let you know if I face any other issues! I am planning to use it in CI as well, but I will probably use the API method via environment variables for that since it will be a separate "automation" Bitwarden account with limited access to the relevant secrets (versus when running locally, where devs are using their own accounts that have access to the shared collection).

Closing the issue, thanks again for you help!
