### ISSUE TITLE
Unable to use session key if client ID/client secret environment variables exist

### ISSUE THREAD

**Issue by ianleeder** [maxlaverse/terraform-provider-bitwarden#124]
We're using devcontainers to attempt to standardise and idiot-proof development as much as possible.  We've configured the container to store the variables:
```
BW_EMAIL
BW_CLIENTID
BW_CLIENTSECRET
```
And we run a script to use the CLI to login, enter the password interactively, and capture the session variable in `BW_SESSION`.  All this in an attempt to not save the password in clear-text anywhere (even environment variables).

Now when we run `terraform apply`, AFAICT it sees 3/4 required variables, and gives an error because it's missing `BW_PASSWORD`.  Even though `BW_SESSION` is present.
```
╷
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/maxlaverse/bitwarden"],
│   on main.tf line 36, in provider "bitwarden":
│   36: provider "bitwarden" {}
│ 
│ "client_id": all of `client_id,client_secret,master_password` must be specified
╵
╷
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/maxlaverse/bitwarden"],
│   on main.tf line 36, in provider "bitwarden":
│   36: provider "bitwarden" {}
│ 
│ "client_secret": all of `client_id,client_secret,master_password` must be specified
╵
```

If I remove the client ID/secret session variables leaving only session & email, the Terraform provider is happy, but now we can't use the CLI to log in and refresh the session variable.

Can you prioritise the session variable, so it works even if no password is provided?

Is there a better way to be doing this?  AFAIK I can't provide the environment variable `BW_SESSION` directly to the provider block.  And I can't pass the client ID/secret to the CLI explicitly (eg if I named the environment variables something else and passed them as arguments).

My versions:
```
$ terraform -v
Terraform v1.7.4
on linux_amd64
+ provider registry.terraform.io/maxlaverse/bitwarden v0.7.2
```

**Comment by ianleeder** [comment]
Even providing the email and session explicitly in the provider block:
```hcl
provider "bitwarden" {
  email = "my email"
  session_key = "my session key"
}
```
It still seems to detect the environment variables, and gives me the same error as above:
```
"client_id": all of `client_id,client_secret,master_password` must be specified
```

**Comment by maxlaverse** [comment]
Hi @ianleeder! Thanks for the detailed explanation. I understood the auto-detection of the type of authentication to perform isn't working well, when variables that are not going to be used are present.

I wouldn't try to change the priority, because I'm sure it's going to break the setup of some of the users. Eventually we could make it configurable.

In the meantime, wouldn't unsetting the Bitwarden related variables that are only used for CLI login, just after you've set 'BW_SESSION', be a solution?

**Comment by ianleeder** [comment]
Yes, I can unset the environment variables for client ID/secret before running terraform. I mainly wasn't sure how long the session key would be valid for. I'm assuming I'll need to regenerate it daily at least.

During my work I find myself opening/closing terminals regularly. So I'd either have to repeatedly unset the variables in every terminal, or remove them globally which hurts regenerating the session key with the CLI. Neither is ideal.

**Comment by maxlaverse** [comment]
Hi @ianleeder,
Just to extra-sure I understand how you use the provider:
* the container image has many development tools, including terraform
* the 3 environments variables `BW_EMAIL`, `BW_CLIENTID ` and `BW_CLIENTSECRET` are always set
* `BW_SESSION` is computed from within the container environment

> I mainly wasn't sure how long the session key would be valid for.

I wondered the same question a year ago and iirc I came to the conclusion that the session key is valid forever for a given local Vault (except after explicit logout), but I never found it explicitly written in any documentation. I would use this as an assumption, rather than daily expiring keys.

> During my work I find myself opening/closing terminals regularly.

So, how does your project work ? The container is the development environment in the form of a terminal, and you start as many as you want ? Eventually you can start an UI as well ? 

> All this in an attempt to not save the password in clear-text anywhere (even environment variables).

It's a reasonable goal and using a _Client ID_ and _Client Secret_ is already a good step I think, because it's something you can invalidate access for at least. Given that your Terraform State is encrypted, I'm not convinced using a _session key_ has a lot of advantages over _client credentials_. More problematic (imho) might be to have the _client credentials_ loaded in my environment _at all time_: any rogue bash script or corrupted NodeJS module could easily recognize and export them, I think. wdyt ?

If we can't find any expiration time to the Bitwarden session key, unsetting the _client credentials_ would become acceptable is that right ?
