### ISSUE TITLE
[FEATURE] Content support for attachments 

### ISSUE THREAD

**Issue by chrthal** [maxlaverse/terraform-provider-bitwarden#146]
Hi @maxlaverse ,
It would be nice to just provide the content of a file like a generated string without providing a path.
Like when creating a file https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file

**Comment by maxlaverse** [comment]
Hi @chrthal 
That's essentially to not have to use the resource you linked right, but support the upload of in-memory attachments out of the box ?
I would be a bit worried about files laying around on the disk if the provider/Terraform crashes. It would be nice if the cli allowed us to pass attachment from stdin instead of requiring them to be on disk.

**Comment by chrthal** [comment]
Yeah, that's what I thought at first, but I haven't had a look at the cli documentation....

For me, the thing is that I run it in a pipeline so that the files are recreated on each run.

**Comment by maxlaverse** [comment]
Hi! I've implemented experimental support for using the provider without requiring the Bitwarden CLI to be installed. If you have the opportunity, please give it a try! Talking directly to the API would open up the possibility of creating attachment without storing them on disk first.

**Comment by maxlaverse** [comment]
Released in [v0.12.0](https://github.com/maxlaverse/terraform-provider-bitwarden/releases/tag/v0.12.0)
